# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de0f8b24288c675cc4b75c76b3649a0d3fb867d439e912d41b82e91382fe2d071df8c818e202b26af30ba112896ad8d82b3e417974861239d58ca19af5cecb13

test:
  secret_key_base: 7c8457e9591293887bb30729a9c5b7af3ce110b58fd0dae1cf0506539195917d16df953416f2af0d7965368e798fc36b8dda99f815d40d977e610c7273cd9543

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
