Student.create!(first_name: "David", last_name: "MacKintosh", cohort: 4)
Student.create!(first_name: "Donald", last_name: "Lessells", cohort: 4)
Student.create!(first_name: "Zak", last_name: "Buys", cohort: 4)
Student.create!(first_name: "Claire", last_name: "Smith", cohort: 3)
Student.create!(first_name: "Craig", last_name: "Morton", cohort: 3)